### ISSUE TITLE
Insert documents into mongodb

### ISSUE THREAD

**Issue by david4096** [Arc39/vcf_to_ga#14]
You might make a collection for each message type (call, variantset...).

Once you have inserted documents into mongodb you can query them from the command line using `mongod`.

**Comment by david4096** [comment]
It's possible to use bulk insert to improve performance.

http://api.mongodb.com/python/current/examples/bulk.html

**Comment by Arc39** [comment]
https://github.com/Arc39/vcf_to_ga/commit/861acf6d193ca95a0f6b5d4e05f5948cfc44537d
