### ISSUE TITLE
Pass script arguments

### ISSUE THREAD

**Issue by david4096** [Arc39/vcf_to_ga#9]
The script should accept the name of the vcf to be processed and an output location as an argument. https://docs.python.org/2/library/argparse.html

**Comment by Arc39** [comment]
``import argparse

parser = argparse.ArgumentParser()
parser.add_argument("-i", "--input", dest="input", help="Input file")
parser.add_argument("-o", "--output", dest="output", help="Output file")
p = parser.parse_args()

assert p.input and p.output

#Main
vcfFile = pysam.VariantFile(p.input)
sys.stdout = open(p.output,"w")``

when in command line:
python program.py -i file.vcf -o output.txt

Is this correct?  It is working.

**Comment by david4096** [comment]
The argparse stuff looks great! For file output you don't need to override stdout. Continue using print for debugging messages and feedback. For writing to file you'll need to create some directory structure and filenames based on the objects unique identifiers.

**Comment by david4096** [comment]
One could set the output type to be either protobuf or JSON. Writing binary to disk is hard to read but we will use both.

**Comment by Arc39** [comment]
https://github.com/Arc39/vcf_to_ga/commit/99338eb009dd4b30664cfadf6e1b8050219b261f
